let a = undefined;

try{
  console.log(a.name);
}
catch(error){
  console.log("Error has occured");
}
